version: '3.8'
services:
  node:
    container_name: surveyer
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
    - './src:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: mongo_surveyer
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge